POST http://localhost:8081/addDatabaseSource
Content-Type: application/json

{
  "databaseName": "local_cingk_schema",
  "url": "jdbc:mysql://localhost:3306/mysql",
  "username": "cingk_mysql",
  "pazzword": "Lv123qwe!",
  "instruction": "mac docker mysql",
  "status": 0
}

###

GET http://localhost:8081/getAllDatabaseSource
Content-Type: application/json
